category_list_banners:
  type: list
  default: "789;none;College Confidential|63;none;Getting to College|634;none;Applying to College|645;none;College and Beyond|631;none;Find Your People"
  description:
    en: "Semicolon delimited in this order:</br> Category ID;Banner color;Heading<br>
    <b>Category ID: </b>The ID of the category below the banner. For example 2 in /c/feedback/2</br>
    <b>Banner color:</b> Any valid color declaration in CSS</br>"
hide_category_color:
  type: bool
  default: false
  description:
    en: "Hide the colored border on category list items"
hide_categories:
  type: list
  default: "77|789|773|24|630|800|3|634"
  description:
    en: "List of categories to hide"
